#!/usr/bin/env python3
"""Audit that every atlas diagram has one crossing per x-sweep slice."""

from __future__ import annotations

from collections import defaultdict
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / "downloads" / "direct-ruling-counter"
sys.path.insert(0, str(ENGINE))

from fig3_direct_ruling_counts import build_polygon_ruling_diagram  # noqa: E402
from verify_multigeodesic_rulings import (  # noqa: E402
    make_parallel_geodesic_arrangement,
)


def records() -> list[dict[str, object]]:
    text = (ROOT / "data" / "cases.js").read_text(encoding="utf-8")
    prefix = "window.RULING_CASES = "
    if not text.startswith("/* Generated by tools/export_cases.py. */\n" + prefix):
        raise ValueError("data/cases.js has an unexpected wrapper")
    payload = text.split(prefix, 1)[1].strip()
    if not payload.endswith(";"):
        raise ValueError("data/cases.js has no terminating semicolon")
    return json.loads(payload[:-1])


def main() -> int:
    reports: list[dict[str, object]] = []
    total_crossings = 0
    atlas = records()
    for record in atlas:
        label = str(record["id"])
        diagram = build_polygon_ruling_diagram(
            label,
            record["vertices"],
            gallery_name="generic-sweep-audit",
        )
        arrangement = make_parallel_geodesic_arrangement(
            diagram.geodesics,
            name=label,
        )
        by_time: dict[object, list[int]] = defaultdict(list)
        for vertex in arrangement.vertices:
            by_time[vertex.position[0]].append(vertex.index)
        collisions = [
            {
                "time": str(time),
                "vertices": vertices,
            }
            for time, vertices in sorted(by_time.items())
            if len(vertices) > 1
        ]
        total_crossings += len(arrangement.vertices)
        if collisions:
            reports.append(
                {
                    "id": label,
                    "crossings": len(arrangement.vertices),
                    "simultaneousBlocks": collisions,
                }
            )
    output = {
        "polygons": len(atlas),
        "crossings": total_crossings,
        "nongenericSweepDiagrams": len(reports),
        "reports": reports,
    }
    print(json.dumps(output, indent=2))
    return 1 if reports else 0


if __name__ == "__main__":
    raise SystemExit(main())
