#!/usr/bin/env python3
"""Export verified direct-ruling cases for the private static prototype."""

from __future__ import annotations

import json
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
SITE_ROOT = HERE.parent
PROJECT_ROOT = SITE_ROOT.parent
ASSET_ROOT = SITE_ROOT / "assets" / "rulings"
DATA_ROOT = SITE_ROOT / "data"

sys.path.insert(0, str(PROJECT_ROOT))

import draw_fig2c_rulings as fig2c  # noqa: E402
import draw_fig3p_rulings as fig3p  # noqa: E402
import draw_p2o4_rulings as style  # noqa: E402


def standalone_svg(svg_inner: str, label: str) -> str:
    escaped_label = (
        label.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 {style.SVG_SIZE} {style.SVG_SIZE}"
  role="img"
  aria-label="{escaped_label}"
  style="--card:#fffdf8;--foreground:#17202a;--viz-series-1:#2766c7;--viz-series-2:#c43b31;--viz-series-3:#269163">
{svg_inner}
</svg>
"""


def export_drawing(case_id: str, drawing: object) -> dict[str, object]:
    filename = f"{case_id}-{drawing.identifier.lower()}.svg"
    destination = ASSET_ROOT / filename
    destination.write_text(
        standalone_svg(
            drawing.svg_inner,
            (
                f"{case_id} {drawing.family}; "
                f"{drawing.disk_eyes} disk eyes; "
                f"{drawing.annular_eyes} annular eyes; "
                f"{drawing.switches} switches"
            ),
        ),
        encoding="utf-8",
    )
    return {
        "identifier": drawing.identifier,
        "family": drawing.family,
        "src": f"assets/rulings/{filename}",
        "mask": drawing.mask_hex,
        "multiplicity": drawing.multiplicity,
        "diskEyes": drawing.disk_eyes,
        "annularEyes": drawing.annular_eyes,
        "switches": drawing.switches,
        "profile": drawing.profile,
    }


def export_fig2c() -> dict[str, object]:
    standard, rational, audit = fig2c.build()
    return {
        "id": "fig2c",
        "title": "Ding–Wei Fig. 2(c)",
        "description": "Triangle with two interior lattice points",
        "vertices": [[0, 0], [4, 0], [1, 2]],
        "counts": {
            "allDisk": int(audit["exactAllDiskRulingCount"]),
            "annular": int(audit["exactAnnularRulingCount"]),
            "total": int(audit["exactTotalRulingCount"]),
        },
        "symmetry": (
            "Two displayed representatives; each has multiplicity 8 "
            "under the selected diagram translation."
        ),
        "standard": {
            **export_drawing("fig2c", standard),
            "genus": 2,
        },
        "rational": [
            export_drawing("fig2c", drawing) for drawing in rational
        ],
    }


def export_fig3p() -> dict[str, object]:
    standard, all_disk, annular, audit = fig3p.build()
    rational = [*all_disk, *annular]
    return {
        "id": "fig3p",
        "title": "Ding–Wei Fig. 3(p)",
        "description": "Quadrilateral with two interior lattice points",
        "vertices": [[0, 0], [3, 0], [3, 1], [0, 2]],
        "counts": {
            "allDisk": int(audit["exactAllDiskRulingCount"]),
            "annular": int(audit["exactAnnularRulingCount"]),
            "total": int(audit["exactTotalRulingCount"]),
        },
        "symmetry": (
            "Eight displayed representatives; each has multiplicity 3 "
            "under (x,y) ↦ (x+1/3,y+1/3)."
        ),
        "standard": {
            **export_drawing("fig3p", standard),
            "genus": 2,
        },
        "rational": [
            export_drawing("fig3p", drawing) for drawing in rational
        ],
    }


def main() -> int:
    ASSET_ROOT.mkdir(parents=True, exist_ok=True)
    DATA_ROOT.mkdir(parents=True, exist_ok=True)
    cases = [export_fig2c(), export_fig3p()]
    if any(
        case["counts"]["total"]
        != case["counts"]["allDisk"] + case["counts"]["annular"]
        for case in cases
    ):
        raise AssertionError("ruling sectors do not sum")
    for case in cases:
        all_disk_multiplicity = sum(
            int(drawing["multiplicity"])
            for drawing in case["rational"]
            if int(drawing["annularEyes"]) == 0
        )
        annular_multiplicity = sum(
            int(drawing["multiplicity"])
            for drawing in case["rational"]
            if int(drawing["annularEyes"]) > 0
        )
        if all_disk_multiplicity != int(case["counts"]["allDisk"]):
            raise AssertionError(
                f"{case['id']}: all-disk multiplicities do not sum"
            )
        if annular_multiplicity != int(case["counts"]["annular"]):
            raise AssertionError(
                f"{case['id']}: annular multiplicities do not sum"
            )
    payload = (
        "/* Generated by tools/export_cases.py. */\n"
        "window.RULING_CASES = "
        + json.dumps(cases, ensure_ascii=False, indent=2)
        + ";\n"
    )
    (DATA_ROOT / "cases.js").write_text(payload, encoding="utf-8")
    print(
        json.dumps(
            {
                "cases": [
                    {
                        "id": case["id"],
                        "counts": case["counts"],
                        "representatives": len(case["rational"]),
                    }
                    for case in cases
                ],
                "usesTropicalCount": False,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
